[deps]
AdvancedMH = "5b7e9947-ddc0-4b3f-9b55-0d8042f74170"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MCMCChainsStorage = "51a256e2-afd8-4c38-88d8-a98ba8ad53ca"
MCMCDiagnosticTools = "be115224-59cd-429b-ad48-344e309966f0"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
